import operator
from typing import Annotated, Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field

# Define dict merger reducer for token usage accumulation
def merge_dict_reducer(left: Dict[str, Any], right: Dict[str, Any]) -> Dict[str, Any]:
    """Merge two dictionaries, accumulating numerical values for duplicate keys (e.g. token counts)."""
    merged = left.copy()
    for key, value in right.items():
        if key in merged:
            if isinstance(merged[key], dict) and isinstance(value, dict):
                merged[key] = merge_dict_reducer(merged[key], value)
            elif isinstance(merged[key], (int, float)) and isinstance(value, (int, float)):
                merged[key] = merged[key] + value
            else:
                merged[key] = value
        else:
            merged[key] = value
    return merged

class SubQuestion(BaseModel):
    """A research sub-question generated during the scoping phase."""
    id: str = Field(description="Unique identifier for the sub-question")
    question: str = Field(description="The research question text")
    status: Literal["pending", "in_progress", "completed", "failed"] = Field(
        default="pending", description="Status: pending, in_progress, completed, failed"
    )
    assigned_researcher: Optional[str] = Field(default=None, description="Identifier of the research agent assigned")
    results_summary: Optional[str] = Field(default=None, description="Summary of research findings for this question")

class ResearchBrief(BaseModel):
    """The structured research brief generated by the scoping agent."""
    topic: str = Field(description="Main research topic")
    scope: str = Field(description="Detailed scope description")
    constraints: List[str] = Field(default_factory=list, description="User or system constraints")
    sub_questions: List[SubQuestion] = Field(default_factory=list, description="Sub-questions to research")
    target_source_count: int = Field(default=20, description="Minimum number of target verified sources")

class SearchResult(BaseModel):
    """Raw search result item returned from a search engine."""
    title: str
    url: str
    content: str
    score: Optional[float] = None
    engine: Optional[str] = None

class VerifiedSource(BaseModel):
    """Scraped source document verified to be valid and accessible."""
    url: str
    title: str
    content: str
    accessible: bool = True
    status_code: Optional[int] = None
    error_message: Optional[str] = None

class Claim(BaseModel):
    """Factual claim extracted from a report section, mapped to supporting sources."""
    claim_id: str
    claim_text: str
    section: str
    supporting_quotes: List[str] = Field(default_factory=list, description="Literal quotes from source content")
    source_urls: List[str] = Field(default_factory=list, description="URLs of supporting source documents")
    verification_status: Literal["verified", "unverified", "failed", "gap"] = Field(
        default="unverified", description="Status: verified, unverified, failed, gap"
    )
    confidence_score: float = Field(default=0.0, ge=0.0, le=1.0, description="Score between 0.0 and 1.0")
    remediation_notes: Optional[str] = None

class Report(BaseModel):
    """Draft or final markdown report compiled by the writer node."""
    title: str
    content: str
    claims: List[Claim] = Field(default_factory=list)
    citations: List[str] = Field(default_factory=list)
    confidence_score: float = Field(default=0.0)

class GraphState(BaseModel):
    """The complete StateGraph state schema flowing through LangGraph nodes."""
    topic: str = Field(default="")
    user_query: str = Field(default="")
    clarification_needed: bool = Field(default=False)
    clarification_question: Optional[str] = None
    clarification_response: Optional[str] = None
    research_brief: Optional[ResearchBrief] = None
    
    # LangGraph state annotations with custom/standard reducers
    sub_questions_state: List[SubQuestion] = Field(default_factory=list)
    search_results: Annotated[List[SearchResult], operator.add] = Field(default_factory=list)
    verified_sources: Annotated[List[VerifiedSource], operator.add] = Field(default_factory=list)
    claims: Annotated[List[Claim], operator.add] = Field(default_factory=list)
    
    draft_report: Optional[Report] = None
    final_report: Optional[Report] = None
    
    errors: Annotated[List[str], operator.add] = Field(default_factory=list)
    token_usage: Annotated[Dict[str, Any], merge_dict_reducer] = Field(default_factory=dict)
    logs: Annotated[List[str], operator.add] = Field(default_factory=list)
